spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:jdbc}

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

server:
  port: 5000
jwt:
  secret: 5Sy1-R-Zj7ajgcabswkEttARiS8Q4Vs9IhYCVAt1bQ0
  expiration: 3600000