spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:jpa}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5000

jwt:
  secret: 5Sy1-R-Zj7ajgcabswkEttARiS8Q4Vs9IhYCVAt1bQ0
  expiration: 3600000

stripe:
  api:
    key: ${STRIPE_API_KEY:sk_test_51RLkHqH55SekC08VBGRFZpHdPck1YoB0EtrscRAjblU6NC4pimDRkzSKLIakjU7D2KkBAIyPOHs8Ah85pv4Sqh4R00K8ScDOMC}