POST http://localhost:5000/api/rentals/return
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6Imx1a2FzeiIsImlhdCI6MTc4MTg2MzkwMiwiZXhwIjoxNzgxODY3NTAyfQ.AoYadetguFYmjrBmWJ5TYKqfv_otgcW9ncnQL0KPAwY