DELETE http://localhost:5000/api/vehicles/eaaa393a-e012-4da0-825e-e65de402fa61
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6ImFkbWluIiwiaWF0IjoxNzgxMDM2NjIwLCJleHAiOjE3ODEwNDAyMjB9.goLoEHgGfLO6P_AR5YnEzKReIuZTQO1Czt56FWwOqtU
Content-Type: application/json

